travis:
  secure:
    BINSTAR_TOKEN: IMMmbrZFnfsvY/IIX56toZ/qBGnK+KmQUzIvEblbe32DwT4Cte0ts4r03CpCSzo0Gi429uEZ72pxw84qUmjAQvoyl91afzIYkVMZ659gIT8CfQkqYr5g8o47AZ3LJImolFfSuHKskInFXnmp3Jt4vPWlkTR9DLLBok9jG5m4zTLjmWK5b4MUx/WEBhN3/zp7X6csIW518wUPagCdJBGoNgtVHLKZPTvTzmS49gq4m/F2/gGjo+G/Lcj19t4w5j9e9tc57zR+jceUtfO9cWA9WqgnC4kUFl79BzGptmMGS1t3HjhGrP0c/a+oRjdmYiqSqjXgorf1IQtgNxaEMyZr2XlxegHaP4U9BHXdVAoBLXRqAJrOQaRorfWQOHnzHSkKd9ot0rdYkMFhZX7R8qFdWQM4vH4QUNx1lLgH7cwjbqZRqGlWtmQAMBLWQGWD7YsHHulghXr1hxbmG9q6lQzw951qyMRu8qxsb05SsaHJqkKxqcgzipTbJdLujrfnRCTt7L8jjdRf1NGzcn6W098tpT5IdgxjWaKSRJ1txCigI/Jc3+5GF8aUNanAyC84mvYWE6bmz5WmV1EZIisH5RhSmiB+bnpkFSDRavGiJtIBA2BiBl6vdsawd7pLnwgfKYDZbULI5nBrL1ESUH9vW5tI62eYhH90yxh1kbYUsEi/jJs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
