travis:
  secure:
    BINSTAR_TOKEN: 5RyX6YO2jqiKjrImqd5wNV6M3nms/BLgiExikEVUbW7nhIv8ZHoj7sMikcMhZORUc7fOItRsTDH2AAlmwlNVcFr18AN+B/ffM+00zvYl33El369fyJKv19gEfnttVbOz7chIpP/tm4hOKzUnejMI5exzqnVRjpDI8ee+CX7mCFsYf91FCKeAuthyYCGa0hW/cOkq2trMmTBxzv1PiTRYZ9HyYA9ZhIiqRzsq+oeSYr52VN7t7emv6z+AZC86OgmvdpUlz20NvWgFybHM+yQV6tcOdccg9zo0kMLamDlrzNBl9UTYfRsZiGdkwNWUZelnZYljPylpTyClLabCAw4rM+ll36N8NKFjldfmlub9LGt1zke8tJcJ6EqXqQX5Qbcf3uM6dQ57gzrwQBnphcLVxvDu13LZQZ+v+FK+kcXUZLRud+xNe2hI1yryg1uNNyVMTyoyVAjv7aZFi/qeVUy3frL1Zxpc/31ks794xmotijw/hzVljyehfcH+CMSbRyKcAIZE02rQvLy1MQN1HZ4YevGBMBU+q3CNZ4nfTidcsdTy3U8kc3Co/+fGRATrcIDrTGKyIgeOIVtv2Na9jZNsEWJzDJFY0nRF1+4oUULKFVa9sQhLcrF3uxaH0v3lxkvaWQBxcqxDiZGWnudZ2A4QJ1Nl4dpEdik4fFDWiEcmPEY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
